### ISSUE TITLE
Feature request: Please provide appimages or similar

### ISSUE THREAD

**Issue by prof7bit** [jonno85uk/chestnut#112]
Many people cant (or won't) install a ton of dependencies on their system only to find out whether it will compile or run or even do what they expect. Appimage would make this much easier. Thank you.

**Comment by prof7bit** [comment]
duplicate, sorry.

**Comment by jonno85uk** [comment]
Hi. Thanks for raising the issue. 
It is unlikely an appimage will be made available anytime soon, if ever, as creating one is non-trivial. 
It is not a high priority for myself.
