### ISSUE TITLE
Support for Olive 0.1.X effects

### ISSUE THREAD

**Issue by oc1024** [jonno85uk/chestnut#57]
Olive will soon transition to a whole new effect infrastructure, and once that is settled, so will [the Community FX repo](https://github.com/cgvirus/Olive-Editor-Community-Effects/). It seems Chestnut preserves the Olive 0.1 effect infrastructure, so being able to load these community effects will increase its usefulness.

**Comment by jonno85uk** [comment]
Sorry. I do not have any intention of using glsl effects in the future of this project.

**Comment by oc1024** [comment]
Isn't the current effects infrastructure already GLSL-based?
